# Generated by Django 2.2.13 on 2020-06-10 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0002_database_migration_state_update'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accesstoken',
            table='oauth2_accesstoken',
        ),
        migrations.AlterModelTable(
            name='client',
            table='oauth2_client',
        ),
        migrations.AlterModelTable(
            name='grant',
            table='oauth2_grant',
        ),
        migrations.AlterModelTable(
            name='refreshtoken',
            table='oauth2_refreshtoken',
        ),
    ]


"""
BEGIN;
--
-- Rename table for accesstoken to oauth2_accesstoken
--
--
-- Rename table for client to oauth2_client
--
--
-- Rename table for grant to oauth2_grant
--
--
-- Rename table for refreshtoken to oauth2_refreshtoken
--
COMMIT;
"""